### ISSUE TITLE
Contributing changes?

### ISSUE THREAD

**Issue by bouncinglime** [hail2u/color-blindness-emulation#1]
I've done some cleanup on the html page, and would love to contribute those back to this project. When I try to sync my changes via the Github desktop app, I'm told that I don't have permission. Is it possible to make this happen?

Thanks!

**Comment by hail2u** [comment]
Send your patch as a pull request.

**Comment by bouncinglime** [comment]
Unfortunately, I am unable to make a pull request because "the source and destination branches are the same." There are no other branches than "master" so I'm not sure what to do.

**Comment by hail2u** [comment]
You should folk a repository at first, then push changes to the folked repository, and then create a pull request from the folked repository.

**Comment by bouncinglime** [comment]
I'm still unable to push changes to the forked repository.

**Comment by bouncinglime** [comment]
aha apparently I have to do it through the website and not through the desktop app. I think the changes should be sent properly now?
